import { MigrationInterface, QueryRunner } from "typeorm";

export class SetupTables1710272422957 implements MigrationInterface {
    name = 'SetupTables1710272422957'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "icon" ("id" SERIAL NOT NULL, "icon" character varying NOT NULL, CONSTRAINT "PK_7860777a14d73877ab2bf5a341c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "imageUrl" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a76c5cd486f7779bd9c319afd27" UNIQUE ("name"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "jobTitle" character varying NOT NULL, "description" character varying(750), "postUrl" character varying, "userSub" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" integer NOT NULL, "columnId" integer NOT NULL, CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "board" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" character varying(50) NOT NULL, "userSub" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_865a0f2e22c140d261b1df80eb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "board_column" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "label" character varying(50), "order" integer NOT NULL, "userSub" character varying NOT NULL, "iconId" integer, "boardId" integer, CONSTRAINT "PK_0273ece23af9b3e55ad6af2fdaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_e66170573cabd565dab1132727d" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_b2eb28ff25950ff6879f2002e10" FOREIGN KEY ("columnId") REFERENCES "board_column"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "board_column" ADD CONSTRAINT "FK_e848337698fa4c5ee6b5b914c19" FOREIGN KEY ("iconId") REFERENCES "icon"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "board_column" ADD CONSTRAINT "FK_7d6b58efcc37a760ffd108eec72" FOREIGN KEY ("boardId") REFERENCES "board"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "board_column" DROP CONSTRAINT "FK_7d6b58efcc37a760ffd108eec72"`);
        await queryRunner.query(`ALTER TABLE "board_column" DROP CONSTRAINT "FK_e848337698fa4c5ee6b5b914c19"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_b2eb28ff25950ff6879f2002e10"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_e66170573cabd565dab1132727d"`);
        await queryRunner.query(`DROP TABLE "board_column"`);
        await queryRunner.query(`DROP TABLE "board"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP TABLE "icon"`);
    }

}
